# Generated by Django 3.1.2 on 2020-10-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricmikrotik',
            name='traff_download',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='metricmikrotik',
            name='traff_uploads',
            field=models.FloatField(),
        ),
    ]
