# Generated by Django 3.1.2 on 2020-10-02 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0003_auto_20201002_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricmikrotik',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
